version: '3.8'

services:
  db:
    image: postgres:16
    container_name: davez_db
    restart: always

    environment:
      POSTGRES_USER: davez_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: davez_dev_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local